artifacts_root : artifacts

data_ingetion:
  root_dir: artifacts/data_ingetion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  local_data_file: artifacts/data_ingetion/data.zip
  unzip_dir: artifacts/data_ingetion